### ISSUE TITLE
Bookmark link broken

### ISSUE THREAD

**Issue by casperboone** [retrography/VUTt#2]
The bookmark link in the README doesn't work. Apparently GitHub's markdown doesn't support javascript links (https://github.com/github/markup/issues/79), it might be an idea to use GitHub Pages?

**Comment by retrography** [comment]
That is, actually, a GitHub page! Just go to
https://retrography.github.io/VUTt

**Comment by casperboone** [comment]
Ah, cool! Missed that ;)
